@extends('Layout.app')
@section('title', 'Scan')

@section('content')

    <div class="form-area">
<div class="scan-container">

<div class="uploadwrapper">
    @if(isset($error))
    <div class="alert alert-danger">
        {{ $error }}
    </div>
@endif
  <div class="file-upload">
    <div class="hidethisbutton">
    <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>
  </div>
    <div class="image-upload-wrap">
         <form class="null-form" action="uploadimg" method="post" enctype="multipart/form-data">
        @csrf
        <input hidden type="text" id="growthprediction" name="genderprediction" value="{{ isset($result['result']) ? $result['result'] : 'null' }}">
        <input hidden type="text" id="growthprobability" name="growthprobability" value="{{ isset($result['probability']) ? $result['probability'] : 'null' }}">

      <input class="file-upload-input" type='file' name="File" onchange="readURL(this);" accept="image/*" />
      <div class="drag-text">
        <h3>Drag and drop a file or select add Image</h3>
      </div>
    </div>
    <div class="file-upload-content">
      <img class="file-upload-image" src="#" alt="your image" />
      <div class="image-title-wrap">
        <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span>
        </button>
        <div class="checkbox-container">
            <label class="checkbox-label" for="check_growth">
                <input type="checkbox" id="check_growth" name="check_growth" value="yes">

                <span class="checkbox-text">Do You Want to Check Growth</span>
            </label>
        </div>
        <button type="submit">submit</button>
    </form>

      </div>
    </div>

  </div>
      </div></div></div>

      <script>
        function readURL(input) {
        if (input.files && input.files[0]) {

          var reader = new FileReader();

          reader.onload = function(e) {
            $('.image-upload-wrap').hide();
            $('.hidethisbutton').hide();
            $('.file-upload-image').attr('src', e.target.result);
            $('.file-upload-content').show();

            $('.image-title').html(input.files[0].name);
          };

          reader.readAsDataURL(input.files[0]);

        } else {
          removeUpload();
        }
      }

      function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.hidethisbutton').show();
        $('.image-upload-wrap').show();
      }
      $('.image-upload-wrap').bind('dragover', function () {
              $('.image-upload-wrap').addClass('image-dropping');
          });
          $('.image-upload-wrap').bind('dragleave', function () {
              $('.image-upload-wrap').removeClass('image-dropping');
      });

      </script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
          // Check if the disclaimer has been shown before
          if (document.cookie.indexOf("disclaimerShown=true") === -1) {
            // Function to show the disclaimer pop-up
            function showDisclaimerPopup() {
              // You can customize the disclaimer message and styling here
              const disclaimerMessage =
                "<h2>Disclaimer</h2>The information provided on this website is intended for general informational purposes only. Our software, as described in the content above, is designed to showcase advanced machine learning capabilities and innovative algorithms. While we strive for the highest level of accuracy, it's important to note that the results generated by the software are based on complex analyses and predictions.\n\nThe software's proficiency in gender detection and growth assessment is a testament to its technological capabilities; however, it should not be considered as a sole and definitive source for critical decisions. Users are advised to exercise caution and seek professional advice when interpreting the results for applications that may have significant implications.";

              // Create a pop-up element
              const popup = document.createElement("div");
              popup.classList.add("popup");
              popup.innerHTML = `<div class="popup-content">
                                    <p>${disclaimerMessage}</p>
                                    <button id="okButton">OK</button>
                                 </div>`;

              // Append the pop-up to the body
              document.body.appendChild(popup);

              // Add an event listener to the OK button
              document.getElementById("okButton").addEventListener("click", function () {
                // Close the pop-up
                document.body.removeChild(popup);

                // Set a cookie to indicate that the disclaimer has been shown
                document.cookie = "disclaimerShown=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/";
              });
            }

            // Call the function to show the disclaimer pop-up
            showDisclaimerPopup();
          }
        });
      </script>

<style>
    .scan-container {
    width: 80%;
    padding: 1px;
    margin: auto auto;
}button {
    display: block;
    padding: 15px 30px;
    font-size: 16px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s, color 0.3s, transform 0.3s;
    outline: none;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    background-color: rgba(37, 31, 31, 0.5);
}

button:hover {

    background-color: rgba(37, 31, 31, 0.8);
    color: #ffffff;
    transform: scale(1.05);
}
.checkbox-container {
    text-align: center;
    margin-top: 20px;
    border: 2px solid red; /* Add red border around the container */
    padding: 10px; /* Add padding for spacing */
    border-radius: 5px; /* Add border radius for rounded corners */
}

.checkbox-wrapper {
    display: inline-block;
    position: relative;
}

.checkbox-label {
    display: inline-block;
    cursor: pointer;
}

.checkbox-text {
    display: inline-block;
    vertical-align: middle;
    margin-left: 10px; /* Adjust margin for spacing */
}
button:active {
    transform: scale(0.95);
}.checkbox-container {
    text-align: center;
    margin-top: 20px;
}

.checkbox-wrapper {
    display: inline-block;
    position: relative;
}

.checkbox-label {
    display: inline-block;
    cursor: pointer;
}

.checkbox-custom {
    position: absolute;
    top: 0;
    left: 0;
    width: 20px;
    height: 20px;
    background-color: #eee;
    border-radius: 5px;
    border: 2px solid #ccc;
    transition: background-color 0.3s, border-color 0.3s;
}

.checkbox-custom::after {
    content: '';
    display: block;
    position: absolute;
    top: 50%;
    left: 50%;
    width: 10px;
    height: 10px;
    border-radius: 2px;
    background-color: #fff;
    transform: translate(-50%, -50%) scale(0);
    transition: transform 0.3s;
}

input[type="checkbox"]:checked + .checkbox-custom::after {
    transform: translate(-50%, -50%) scale(1);
}

.checkbox-text {
    margin-left: 30px;
    display: inline-block;
    vertical-align: middle;
}

/* Hover and Focus Effects */
.checkbox-label:hover .checkbox-custom,
.checkbox-label:focus .checkbox-custom {
    background-color: #ddd;
    border-color: #999;
}

.checkbox-label:hover .checkbox-custom::after,
.checkbox-label:focus .checkbox-custom::after {
    background-color: #fff;
}

</style>
@endsection

