@extends('Layout.app')
@section('content')
<main >
<div class="container">

<div class="uploadwrapper">
        <form action="#">
      <a href="report"><input class="file-input" type="file" name="file" hidden><i class="fas fa-cloud-upload-alt"></i>

          <p>Browse File to Upload</p>
        </a>     </form>
        <section class="progress-area"></section>
        <section class="uploaded-area"></section>
      </div></div>
      <script>
        const form = document.querySelector("form"),
fileInput = document.querySelector(".file-input"),
progressArea = document.querySelector(".progress-area"),
uploadedArea = document.querySelector(".uploaded-area");
form.addEventListener("click", () =>{
  fileInput.click();
});
fileInput.onchange = ({target})=>{
  let file = target.files[0];
  if(file){
    let fileName = file.name;
    if(fileName.length >= 12){
      let splitName = fileName.split('.');
      fileName = splitName[0].substring(0, 13) + "... ." + splitName[1];
    }
    uploadFile(fileName);
  }
}
function uploadFile(name){
  let xhr = new XMLHttpRequest();
  xhr.open("POST", "php/upload.php");
  xhr.upload.addEventListener("progress", ({loaded, total}) =>{
    let fileLoaded = Math.floor((loaded / total) * 100);
    let fileTotal = Math.floor(total / 1000);
    let fileSize;
    (fileTotal < 1024) ? fileSize = fileTotal + " KB" : fileSize = (loaded / (1024*1024)).toFixed(2) + " MB";
    let progressHTML = `<li class="row">
                          <i class="fas fa-file-alt"></i>
                          <div class="content">
                            <div class="details">
                              <span class="name">${name} • Uploading</span>
                              <span class="percent">${fileLoaded}%</span>
                            </div>
                            <div class="progress-bar">
                              <div class="progress" style="width: ${fileLoaded}%"></div>
                            </div>
                          </div>
                        </li>`;
    uploadedArea.classList.add("onprogress");
    progressArea.innerHTML = progressHTML;
    if(loaded == total){
      progressArea.innerHTML = "";
      let uploadedHTML = `<li class="row">
                            <div class="content upload">
                              <i class="fas fa-file-alt"></i>
                              <div class="details">
                                <span class="name">${name} • Uploaded</span>
                                <span class="size">${fileSize}</span>
                              </div>
                            </div>
                            <i class="fas fa-check"></i>
                          </li>`;
      uploadedArea.classList.remove("onprogress");
      uploadedArea.insertAdjacentHTML("afterbegin", uploadedHTML);
    }
  });
  let data = new FormData(form);
  xhr.send(data);
}
      </script>
      <script>
        document.addEventListener("DOMContentLoaded", function() {
  // Function to show the disclaimer pop-up
  function showDisclaimerPopup() {
    // You can customize the disclaimer message and styling here
    const disclaimerMessage = "<h2>Disclaimer</h2>The information provided on this website is intended for general informational purposes only. Our software, as described in the content above, is designed to showcase advanced machine learning capabilities and innovative algorithms. While we strive for the highest level of accuracy, it's important to note that the results generated by the software are based on complex analyses and predictions.\n\nThe software's proficiency in gender detection and growth assessment is a testament to its technological capabilities; however, it should not be considered as a sole and definitive source for critical decisions. Users are advised to exercise caution and seek professional advice when interpreting the results for applications that may have significant implications.";

    // Create a pop-up element
    const popup = document.createElement("div");
    popup.classList.add("popup");
    popup.innerHTML = `<div class="popup-content">
                          <p>${disclaimerMessage}</p>
                          <button id="okButton">OK</button>
                       </div>`;

    // Append the pop-up to the body
    document.body.appendChild(popup);

    // Add an event listener to the OK button
    document.getElementById("okButton").addEventListener("click", function() {
      // Close the pop-up
      document.body.removeChild(popup);

      // Redirect to the scan page (change the URL accordingly)

    });
  }

  // Call the function to show the disclaimer pop-up
  showDisclaimerPopup();
});
      </script>
</main>
@endsection
