
<script>
    function readURL(input) {
    if (input.files && input.files[0]) {

      var reader = new FileReader();

      reader.onload = function(e) {
        $('.image-upload-wrap').hide();
        $('.hidethisbutton').hide();
        $('.file-upload-image').attr('src', e.target.result);
        $('.file-upload-content').show();

        $('.image-title').html(input.files[0].name);
      };

      reader.readAsDataURL(input.files[0]);

    } else {
      removeUpload();
    }
  }

  function removeUpload() {
    $('.file-upload-input').replaceWith($('.file-upload-input').clone());
    $('.file-upload-content').hide();
    $('.hidethisbutton').show();
    $('.image-upload-wrap').show();
  }
  $('.image-upload-wrap').bind('dragover', function () {
          $('.image-upload-wrap').addClass('image-dropping');
      });
      $('.image-upload-wrap').bind('dragleave', function () {
          $('.image-upload-wrap').removeClass('image-dropping');
  });

  </script>
  <script>
         document.addEventListener("DOMContentLoaded", function() {
    // Function to show the disclaimer pop-up
    function showDisclaimerPopup() {
      // You can customize the disclaimer message and styling here
      const disclaimerMessage = "<h2>Disclaimer</h2>The information provided on this website is intended for general informational purposes only. Our software, as described in the content above, is designed to showcase advanced machine learning capabilities and innovative algorithms. While we strive for the highest level of accuracy, it's important to note that the results generated by the software are based on complex analyses and predictions.\n\nThe software's proficiency in gender detection and growth assessment is a testament to its technological capabilities; however, it should not be considered as a sole and definitive source for critical decisions. Users are advised to exercise caution and seek professional advice when interpreting the results for applications that may have significant implications.";

      // Create a pop-up element
      const popup = document.createElement("div");
      popup.classList.add("popup");
      popup.innerHTML = `<div class="popup-content">
                            <p>${disclaimerMessage}</p>
                            <button id="okButton">OK</button>
                         </div>`;

      // Append the pop-up to the body
      document.body.appendChild(popup);

      // Add an event listener to the OK button
      document.getElementById("okButton").addEventListener("click", function() {
        // Close the pop-up
        document.body.removeChild(popup);

        // Redirect to the scan page (change the URL accordingly)

      });
    }

    // Call the function to show the disclaimer pop-up
    showDisclaimerPopup();
  });
  </script>
